name: CICD for GO

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2.3.4
      - name: Setup go
        uses: actions/setup-go@v2.1.3
      - name: Check Go Version
        run: |
          go version
