name: CICD for GO

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2.3.4
        
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        
      - name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
          which go
          
      - name: Run unit tests
        run: |
          go test -v ./... | $(GOPATH)/bin/go2xunit -output test_report.xml
          
      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test_report.xml
