name: CICD for GO

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2.3.4
        
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        
      - name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
          
      - name: Run Unit Tests
        run: |
          go test -v ./... | go2xunit >report.xml
          
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: report.xml
