name: CICD for GO

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout my codes
        uses: actions/checkout@v2.3.4
        
      - if: ${{success()}}  
        name: Setup go
        uses: actions/setup-go@v2.1.3
        
      - if: ${{success()}}    
        name: Install dependencies
        run: |
          go get github.com/tebeka/go2xunit
          
      - if: ${{success()}}      
        name: Run unit tests
        run: |
          go test -v ./... | /home/runner/go/bin/go2xunit -output test_report.xml
          
      - if: ${{success()}}      
        name: Publish unit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test_report.xml
